### ISSUE TITLE
unexpected set_css call + others

### ISSUE THREAD

**Issue by tomholub** [CryptUp/cryptup-browser#897]
```
Error: tool.browser.message.listen_background error: handler "set_css" not set
    at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3581:13)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1381:17
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:149:26)
    at messageListener (extensions::messaging:215:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)


details: Message sender stack:
    at Object.browser_message_send [as send] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1329:174)
    at Object.send_message_to_main_window (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.js:159:82)
    at resize_reply_box (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:895:13)
    at HTMLDocument.$.ready (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:190:31)
    at i (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27151)
    at Object.add [as done] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:29515)
    at initialize_compose_box (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:190:19)
```

**Comment by tomholub** [comment]
```
Error: tool.browser.message.listen_background error: handler "close_new_message" not set
    at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3581:13)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1381:17
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:149:26)
    at messageListener (extensions::messaging:215:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)


details: Message sender stack:
    at Object.browser_message_send [as send] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1329:174)
    at HTMLSpanElement.close_message (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.js:275:30)
    at HTMLSpanElement.dispatch (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:3:7537)
    at HTMLSpanElement.r.handle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:3:5620)
```

**Comment by tomholub** [comment]
```
Error: tool.browser.message.listen_background error: handler "notification_show" not set
    at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3581:13)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1381:17
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:149:26)
    at messageListener (extensions::messaging:215:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)


details: Message sender stack:
    at Object.browser_message_send [as send] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1329:174)
    at Object.send_message_to_main_window (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.js:159:82)
    at app.email_provider_message_send.then.response (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:723:11)
    at <anonymous>
```

**Comment by tomholub** [comment]
```
Error: tool.browser.message.listen_background error: handler "scroll" not set
    at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3581:13)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1381:17
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:149:26)
    at messageListener (extensions::messaging:215:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)


details: Message sender stack:
    at Object.browser_message_send [as send] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1329:174)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/reply_pubkey_mismatch.js:18:22
```
